apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkedin-app
  namespace: linkedin-app
  annotations:
  argocd-image-updater.argoproj.io/image-list: linkedin-app=rudyfontys/linkedin-app
  argocd-image-updater.argoproj.io/linkedin-app.update-strategy: latest
  argocd-image-updater.argoproj.io/linkedin-app.allow-tags: regexp:^1\\.0\\.\\d+$
  argocd-image-updater.argoproj.io/write-back-method: git
  argocd-image-updater.argoproj.io/write-back-target: kubernetes/deployment.yaml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: linkedin-app
  template:
    metadata:
      labels:
        app: linkedin-app
    spec:
      containers:
      - name: linkedin-app
        image: rudyfontys/linkedin-app:latest # Dit wordt automatisch bijgewerkt door ArgoCD
        ports:
        - containerPort: 80
        env:
        - name: LINKEDIN_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: linkedin-api
              key: client_id
        - name: LINKEDIN_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: linkedin-api
              key: client_secret