apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkedin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkedin-app
  template:
    metadata:
      labels:
        app: linkedin-app
    spec:
      containers:
      - name: linkedin-app
        image: ${{ secrets.DOCKER_HUB_USERNAME }}/linkedin-app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"