apiVersion: argoproj.io/v1alpha1 # Argo CD Application (voor automatische updates), dit kan veranderen...
kind: Application
metadata:
  name: linkedinlogin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RudyFontys/LinkedinLogin.git  # Mijn repo
    targetRevision: HEAD
    path: kubernetes  # Map waar de YAML-bestanden staan
    # helm: {}  # Optioneel: gebruik Helm, maar dat wil ik niet...
  destination:
    server: https://kubernetes.default.svc
    namespace: linkedinlogin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true