# linkedin-app-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkedin-app-pvc
  namespace: linkedin-app
spec:
  accessModes:
    - ReadWriteMany  # Meerdere pods kunnen schrijven
  storageClassName: longhorn  # Gebruik Longhorn als storage provider
  resources:
    requests:
      storage: 1Gi  # 1GB opslag 