apiVersion: v1
kind: Secret
metadata:
  name: linkedin-api
  namespace: linkedin-app
type: Opaque
data:
  client_id: Nzh3bTA0M2JsYWYycnQ=  # dit is gegenereerd in Kubernetes met echo -n "MIJN_CLIENT_ID" | base64 
  client_secret: V1BMX0FQMS5ybDBHbWdVM0dkVFR1WGl5LmJ1QzFBUT09  # dit is gegenereerd in Kubernetes met echo -n "MIJN_CLIENT_SECRET" | base64