apiVersion: v1
kind: Service
metadata:
  name: linkedin-app-service
spec:
  selector:
    app: linkedin-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 10.255.255.230